---
title: Remembering Columbus
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: rememberingcolumbus@gmail.com
description: 'Logistical assistance and resources for families who have lost loved
  ones (financial assistance, information regarding funerals. Memorializing the deceased.
  Emotional support for families of the deceased. '
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: rememberingcolumbus
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
